//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Inter
{
    using System;
    using System.Collections.Generic;
    
    public partial class cadastro_produto
    {
        public int id { get; set; }
        public string descricao { get; set; }
        public string marcaitem { get; set; }
        public string unidademedida { get; set; }
        public string departamento { get; set; }
        public System.DateTime datacadastro { get; set; }
    }
}
