//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Inter
{
    using System;
    using System.Collections.Generic;
    
    public partial class compra
    {
        public int idcompra { get; set; }
        public int idcotacao { get; set; }
        public System.DateTime datacotacao { get; set; }
        public string funcionariosolicit { get; set; }
        public string departamento { get; set; }
        public string funcionarioaprov { get; set; }
        public string prazo { get; set; }
        public string pagamento { get; set; }
    }
}
