//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Inter
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotacao
    {
        public int idcotacao { get; set; }
        public System.DateTime datacotacao { get; set; }
        public int idreq { get; set; }
        public System.DateTime datareq { get; set; }
        public string funcioanriosolicit { get; set; }
        public string departamento { get; set; }
        public string valor { get; set; }
        public string funcionarioaprov { get; set; }
    
        public virtual cotacao cotacao1 { get; set; }
        public virtual cotacao cotacao2 { get; set; }
        public virtual requisicao requisicao { get; set; }
    }
}
