//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Inter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bancodadosEntities : DbContext
    {
        public bancodadosEntities()
            : base("name=bancodadosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cadastro_fornecedor> cadastro_fornecedor { get; set; }
        public virtual DbSet<cadastro_funcionario> cadastro_funcionario { get; set; }
        public virtual DbSet<cadastro_produto> cadastro_produto { get; set; }
        public virtual DbSet<compra> compra { get; set; }
        public virtual DbSet<cotacao> cotacao { get; set; }
        public virtual DbSet<requisicao> requisicao { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
