//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Inter
{
    using System;
    using System.Collections.Generic;
    
    public partial class requisicao
    {
        public int idreq { get; set; }
        public System.DateTime datareq { get; set; }
        public int iditem { get; set; }
        public string descricao { get; set; }
        public int quantidade { get; set; }
        public string comentario { get; set; }
        public string funcionariorequisit { get; set; }
    
        public virtual cotacao cotacao { get; set; }
    }
}
